# Generated by Django 5.1.4 on 2025-08-25 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_employee', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_administration', models.BooleanField(default=False)),
                ('is_hr', models.BooleanField(default=False)),
                ('rank', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('work_days', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('holidays', models.IntegerField(blank=True, null=True)),
                ('overseas_days', models.IntegerField(default=0)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_join', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SICK LEAVE', 'Sick Leave'), ('ANNUAL LEAVE', 'Annual Leave')], max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.TextField()),
                ('no_of_days', models.IntegerField(editable=False)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to='medical_certificates/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_leave', models.IntegerField(default=30)),
                ('sick_leave', models.IntegerField(default=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('vessel_name', models.CharField(blank=True, default='', max_length=255)),
                ('purchase_and_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('invoice_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency_code', models.CharField(default='AED', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGN', 'Assign'), ('ONGOING', 'Ongoing'), ('HOLD', 'Hold'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=100)),
                ('category', models.CharField(choices=[('OVERSEAS', 'Overseas'), ('ANCHORAGE', 'Anchorage'), ('HOLIDAY_WORKING', 'Holiday Working'), ('AT_BERTH', 'At Berth')], default='AT_BERTH', max_length=50)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='project_attachments/')),
                ('job_card', models.FileField(blank=True, null=True, upload_to='job_cards/')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'is_manager': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='Admin.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateField()),
                ('time_stop', models.DateField()),
                ('employee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Admin.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='Admin.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employees', models.ManyToManyField(limit_choices_to={'is_employee': True}, related_name='teams_assigned', to='Admin.employee')),
                ('manager', models.ForeignKey(limit_choices_to={'is_manager': True}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_teams', to='Admin.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='Admin.project')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMemberStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ASSIGN', 'Assign'), ('ONGOING', 'Ongoing'), ('HOLD', 'Hold'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='ASSIGN', max_length=100)),
                ('notes', models.TextField(blank=True, max_length=2000, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('manager_approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_statuses', to='Admin.employee')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members_status', to='Admin.team')),
            ],
            options={
                'unique_together': {('team', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(default='UNKNOWN', max_length=100)),
                ('new_status', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to='Admin.employee')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_logs', to='Admin.project')),
                ('team_member_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='Admin.teammemberstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('log_out_time', models.DateTimeField(blank=True, null=True)),
                ('total_hours_of_work', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, choices=[('DMC', 'DMC Warehouse'), ('DMC_PRT', 'DMC Port'), ('FUJ', 'FUJ'), ('KFK', 'KFK'), ('ABU', 'Abu Dhabi'), ('BDO', 'Bur Dubai Office'), ('SHJ_KP', 'Sharjah Khalid Port'), ('SHJ_HP', 'Sharjah Hamriya Port'), ('AJM_PRT', 'Ajman Port'), ('ABU_KP', 'Abu Dhabi Khalifa Port'), ('ABU_MP', 'Abu Dhabi Mussafah Port'), ('RAK_JZP', 'RAK Al Jazeera Port'), ('RAK_MCP', 'RAK Maritime City'), ('RAK_SRP', 'RAK Steven Rock Port'), ('DXB_DMC', 'Dubai Maritime City Port'), ('DXB_PR', 'Port Rashid'), ('DXB_HP', 'Dubai Hamriya Port'), ('DXB_MHJ', 'Dubai Marina Harbor Jumeirah'), ('DXB_AJD', 'Al Jadaf Port Dubai'), ('OVERSEAS', 'Overseas')], max_length=20, null=True)),
                ('attendance_status', models.CharField(blank=True, choices=[('PRESENT', 'Present'), ('WORK FROM HOME', 'Work from Home')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('travel_in_time', models.DateTimeField(blank=True, null=True)),
                ('travel_out_time', models.DateTimeField(blank=True, null=True)),
                ('total_travel_time', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_attendance', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_set', to='Admin.employee')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_set', to='Admin.project')),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='Admin.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('vessel', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.CharField(blank=True, max_length=100, null=True)),
                ('imo_no', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('job_scope', models.TextField(blank=True, null=True)),
                ('job_instructions', models.TextField(blank=True, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('all_members', models.ManyToManyField(blank=True, related_name='all_assigned_work_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_work_orders', to=settings.AUTH_USER_MODEL)),
                ('job_assigned_to', models.ManyToManyField(blank=True, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workorder', to='Admin.project')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='Admin.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spares', to='Admin.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Admin.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('finish_time', models.TimeField(blank=True, null=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='Admin.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work_order_images/')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Admin.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='Admin.workorder')),
            ],
        ),
    ]
