# Generated by Django 5.1.4 on 2024-12-17 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('work_days', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('holidays', models.IntegerField(blank=True, null=True)),
                ('overseas_days', models.IntegerField(default=0)),
                ('project_purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('project_invoice', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.project')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employee Details',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField()),
                ('log_out_time', models.DateTimeField()),
                ('total_hours_of_work', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('DMC', 'DMC Warehouse'), ('FUJ', 'FUJ'), ('KFK', 'KFK'), ('ABU', 'Abu Dhabi'), ('BDO', 'Bur Dubai Office '), ('OVERSEAS', 'Overseas'), ('WORK FROM HOME', 'work from home'), ('SICK LEAVE', 'sick leave'), ('ANNUAL LEAVE', 'annual leave')], max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_set', to='Admin.employee')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
            },
        ),
    ]
