# Generated by Django 5.1.4 on 2025-08-25 10:36

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordertime',
            name='estimated_hours',
            field=models.DecimalField(max_digits=5, decimal_places=2, default=0, editable=False),
        ),
    ]

