# Generated by Django 5.1.4 on 2024-12-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_alter_attendance_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='invoice_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
