# Generated by Django 5.1.4 on 2026-01-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGN', 'Assign'), ('ONGOING', 'Ongoing'), ('QUOTED', 'Quoted'), ('HOLD', 'Hold'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=100),
        ),
    ]
