# Generated by Django 5.1.4 on 2026-01-14 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorderimage',
            name='name',
            field=models.CharField(default='Untitled Image', max_length=100),
        ),
        migrations.CreateModel(
            name='SpareConsumed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumed_spares', to='Admin.workorder')),
            ],
        ),
    ]
