# Generated by Django 5.1.4 on 2025-01-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_attendance_travel_in_time_attendance_travel_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='location',
            field=models.CharField(blank=True, choices=[('DMC', 'DMC Warehouse'), ('FUJ', 'FUJ'), ('KFK', 'KFK'), ('ABU', 'Abu Dhabi'), ('BDO', 'Bur Dubai Office'), ('OVERSEAS', 'Overseas')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('PRESENT', 'Present'), ('WORK FROM HOME', 'Work from Home'), ('SICK LEAVE', 'Sick Leave'), ('ANNUAL LEAVE', 'Annual Leave'), ('CASUAL LEAVE', 'Casual Leave')], max_length=20, null=True),
        ),
    ]
