# Generated by Django 5.1.4 on 2026-01-19 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_workorderimage_description_workorderimage_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpareConsumed',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('work_order', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='consumed_spares',
                    to='Admin.workorder',
                )),
            ],
        ),
    ]

