# Generated by Django 5.1.4 on 2025-01-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_attendance_attendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_status',
            field=models.CharField(blank=True, choices=[('PRESENT', 'Present'), ('LEAVE', 'Leave'), ('WORK FROM HOME', 'Work from Home'), ('SICK LEAVE', 'Sick Leave'), ('ANNUAL LEAVE', 'Annual Leave'), ('CASUAL LEAVE', 'Casual Leave')], max_length=20, null=True),
        ),
    ]
