# Generated by Django 5.1.4 on 2025-01-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('OVERSEAS', 'Overseas'), ('ANCHORAGE', 'Anchorage'), ('HOLIDAY_WORKING', 'Holiday Working')], default='OVERSEAS', max_length=50),
        ),
    ]
