# Generated by Django 5.1.4 on 2025-01-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassignment',
            name='time_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projectassignment',
            name='time_stop',
            field=models.DateField(),
        ),
    ]
