# Generated by Django 5.1.4 on 2025-01-13 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_set', to='Admin.project'),
        ),
    ]
