# Generated by Django 5.1.4 on 2025-01-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_employee_is_employee_employee_is_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectassignment',
            name='employee',
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='employee',
            field=models.ManyToManyField(to='Admin.employee'),
        ),
    ]
