# Generated by Django 5.1.4 on 2025-01-16 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_remove_projectassignment_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectassignment',
            name='employee',
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Admin.employee'),
        ),
    ]
