# Generated by Django 5.1.4 on 2025-01-21 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_remove_projectassignment_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_manager': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='Admin.employee'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employees', models.ManyToManyField(limit_choices_to={'is_employee': True}, related_name='teams', to='Admin.employee')),
                ('manager', models.OneToOneField(limit_choices_to={'is_manager': True}, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='Admin.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='Admin.project')),
            ],
        ),
    ]
