# Generated by Django 5.1.4 on 2025-01-21 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0018_project_manager_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='employees',
            field=models.ManyToManyField(limit_choices_to={'is_employee': True}, related_name='teams_assigned', to='Admin.employee'),
        ),
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'is_manager': True}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_teams', to='Admin.employee'),
        ),
    ]
