# Generated by Django 5.1.4 on 2025-01-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0021_project_created_at_alter_teammemberstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
