# Generated by Django 5.1.4 on 2025-01-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0023_remove_teammemberstatus_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammemberstatus',
            name='created',
        ),
        migrations.RemoveField(
            model_name='teammemberstatus',
            name='notes',
        ),
        migrations.AddField(
            model_name='teammemberstatus',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
