# Generated by Django 5.1.4 on 2025-01-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0025_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='old_status',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='previous_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='new_status',
            field=models.CharField(max_length=100),
        ),
    ]
