# Generated by Django 5.1.4 on 2025-01-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0026_remove_activitylog_changed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammemberstatus',
            name='notes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
