# Generated by Django 5.1.4 on 2025-01-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0027_teammemberstatus_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='notes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
