# Generated by Django 5.1.4 on 2025-01-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0029_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('SICK LEAVE', 'Sick Leave'), ('ANNUAL LEAVE', 'Annual Leave'), ('CASUAL LEAVE', 'Casual Leave')], max_length=50),
        ),
    ]
