# Generated by Django 5.1.4 on 2025-01-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0030_leave_approval_status_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_travel_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
