# Generated by Django 5.1.4 on 2025-01-31 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0032_remove_attendance_total_travel_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='travel_time',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.traveltime'),
        ),
    ]
