# Generated by Django 5.1.4 on 2025-02-05 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0038_employee_address_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to='Admin.employee'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_logs', to='Admin.project'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='previous_status',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='team_member_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='Admin.teammemberstatus'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_status',
            field=models.CharField(blank=True, choices=[('PRESENT', 'Present'), ('WORK FROM HOME', 'Work from Home')], max_length=20, null=True),
        ),
    ]
