# Generated by Django 5.1.4 on 2025-02-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0039_activitylog_changed_by_activitylog_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
