# Generated by Django 5.1.4 on 2025-02-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0040_project_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='currency_code',
            field=models.CharField(default='AED', max_length=10),
        ),
    ]
