# Generated by Django 5.1.4 on 2025-02-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0043_project_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
