# Generated by Django 5.1.4 on 2025-02-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0044_project_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='medical_certificates/'),
        ),
    ]
