# Generated by Django 5.1.4 on 2025-02-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0045_leave_medical_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='project_attachments/'),
        ),
    ]
