# Generated by Django 5.1.4 on 2025-02-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0047_employee_is_administration_employee_is_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammemberstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-02-20 12:00:00'),
            preserve_default=False,
        ),
    ]
