# Generated by Django 5.1.4 on 2025-02-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0048_teammemberstatus_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammemberstatus',
            name='created_at',
        ),
    ]
