# Generated by Django 5.1.4 on 2025-05-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0049_remove_teammemberstatus_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='location',
            field=models.CharField(blank=True, choices=[('DMC', 'DMC Warehouse'), ('FUJ', 'FUJ'), ('KFK', 'KFK'), ('ABU', 'Abu Dhabi'), ('BDO', 'Bur Dubai Office'), ('SHJ_KP', 'Sharjah Khalid Port'), ('SHJ_HP', 'Sharjah Hamriya Port'), ('AJM_PRT', 'Ajman Port'), ('ABU_KP', 'Abu Dhabi Khalifa Port'), ('ABU_MP', 'Abu Dhabi Mussafah Port'), ('RAK_JZP', 'RAK Al Jazeera Port'), ('RAK_MCP', 'RAK Maritime City'), ('RAK_SRP', 'RAK Steven Rock Port'), ('DXB_DMC', 'Dubai Maritime City Port'), ('DXB_PR', 'Port Rashid'), ('DXB_HP', 'Dubai Hamriya Port'), ('DXB_MHJ', 'Dubai Marina Harbor Jumeirah'), ('DXB_AJD', 'Al Jadaf Port Dubai'), ('OVERSEAS', 'Overseas')], max_length=20, null=True),
        ),
    ]
