# Generated by Django 5.1.4 on 2025-06-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0051_alter_attendance_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='job_card',
            field=models.FileField(blank=True, null=True, upload_to='job_cards/'),
        ),
    ]
