# Generated by Django 5.1.4 on 2025-06-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0052_project_job_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammemberstatus',
            name='manager_approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='teammemberstatus',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
