# Generated by Django 5.1.4 on 2025-06-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0057_workorder_tool_spare_document_workorderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorderdetail',
            name='job_instructions',
        ),
        migrations.AddField(
            model_name='workorder',
            name='job_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
