# Generated by Django 5.1.4 on 2025-06-30 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0058_remove_workorderdetail_job_instructions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='job_assigned_to',
        ),
        migrations.AddField(
            model_name='workorder',
            name='job_assigned_to',
            field=models.ManyToManyField(related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
