# Generated by Django 5.1.4 on 2025-06-30 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0059_remove_workorder_job_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workorder', to='Admin.project'),
        ),
    ]
