# Generated by Django 5.1.4 on 2025-08-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0061_vessel_alter_document_work_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='project_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='project_images',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
