# Generated by Django 5.1.4 on 2025-08-07 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0062_workorder_project_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='project_images',
        ),
        migrations.CreateModel(
            name='WorkOrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work_order_images/')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Admin.workorder')),
            ],
        ),
    ]
