# Generated by Django 5.1.4 on 2025-08-07 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0063_remove_workorder_project_images_workorderimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_work_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='imo_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='job_assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='job_scope',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='vessel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_order_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
