# Generated by Django 5.1.4 on 2025-08-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0064_alter_workorder_assigned_date_alter_workorder_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('OVERSEAS', 'Overseas'), ('ANCHORAGE', 'Anchorage'), ('HOLIDAY_WORKING', 'Holiday Working'), ('AT_BERTH', 'At Berth')], default='AT_BERTH', max_length=50),
        ),
    ]
