# Generated by Django 5.1.4 on 2025-08-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0066_alter_project_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='vessel_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
