# Generated by Django 5.2 on 2026-01-23 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0006_create_spareconsumed'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vessel_name', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('INSPECTION', 'Inspection'), ('JOB', 'Job')], max_length=20)),
                ('service_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_hours', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('ot_hours', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('ot_type', models.CharField(blank=True, choices=[('WEEKDAY', 'Week Day'), ('HOLIDAY', 'Holiday')], max_length=20, null=True)),
                ('location_type', models.CharField(choices=[('ANCHORAGE', 'Anchorage'), ('SAILING', 'Sailing')], max_length=20)),
                ('is_holiday', models.BooleanField(default=False)),
                ('normal_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('ot_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_logs', to='Admin.employee')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_logs', to='Admin.project')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['employee', 'date'], name='service_log_employe_eab8d1_idx'), models.Index(fields=['project'], name='service_log_project_7cc483_idx')],
            },
        ),
    ]
