# Generated by Django 5.2 on 2026-01-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeservicelog',
            name='ot_type',
            field=models.CharField(blank=True, choices=[('WEEKDAY', 'Week Day'), ('HOLIDAY', 'Holiday')], default='WEEKDAY', max_length=20, null=True),
        ),
    ]
